const SUFFIXES_ACADEMIQUES = [
  '.edu',
  '.ac.uk',
  '.ac.be',
  '.ac.jp',
  '.ac.nz',
  '.ac.za',
  '.ac.il',
  '.ac.kr',
  '.ac.in',
  '.ac.at',
  '.ac.cn',
  '.edu.au',
  '.edu.br',
  '.edu.cn',
  '.edu.co',
  '.edu.mx',
  '.edu.ar',
  '.edu.pe',
  '.edu.sg',
  '.edu.hk',
  '.edu.tr',
  '.edu.pl',
  '.edu.es',
  '.edu.it',
  '.edu.pt',
  '.edu.lb',
  '.edu.ma',
  '.edu.tn',
  '.edu.dz',
  '.edu.eg',
  '.edu.sa',
  '.edu.vn',
  '.edu.my',
  '.edu.ph',
  '.edu.pk',
  '.edu.ng',
  '.edu.gh',
  '.edu.ec',
  '.edu.uy',
  '.edu.ve',
  '.edu.bo',
  '.edu.do',
  '.edu.cu',
  '.edu.gt',
  '.edu.hn',
  '.edu.ni',
  '.edu.pa',
  '.edu.py',
  '.edu.sv',
  '.edu.kz',
  '.edu.ua',
  '.edu.ge',
  '.edu.al',
  '.edu.mk',
  '.edu.rs',
  '.edu.ba',
  '.edu.jo',
  '.edu.kw',
  '.edu.qa',
  '.edu.om',
  '.edu.bh',
  '.edu.iq',
  '.edu.ye',
  '.edu.sy',
  '.edu.ps',
  '.edu.bd',
  '.edu.np',
  '.edu.lk',
  '.edu.mm',
  '.edu.kh',
  '.edu.la',
  '.edu.mn',
  '.edu.tw',
  '.edu.mo',
  '.edu.bn',
  '.edu.et',
  '.edu.ke',
  '.edu.tz',
  '.edu.ug',
  '.edu.zm',
  '.edu.zw',
  '.edu.mw',
  '.edu.mz',
  '.edu.rw',
  '.edu.sd',
  '.edu.ly',
  '.edu.jm',
  '.edu.tt',
  '.edu.bs',
  '.edu.bb',
  '.edu.bz',
  '.edu.gy',
  '.edu.sr',
  '.edu.ht',
  '.edu.pr',
];

const PREFIXES_ETUDIANTS = [
  'etu.',
  'etud.',
  'etudiant.',
  'etudiants.',
  'student.',
  'students.',
  'stud.',
];

const MOTIFS_FRANCAIS = [
  /(^|\.)univ-[a-z0-9-]+\.fr$/,
  /(^|\.)u-[a-z0-9-]+\.fr$/,
  /(^|\.)sorbonne-universite\.fr$/,
  /(^|\.)sorbonne-nouvelle\.fr$/,
  /(^|\.)paris-sorbonne\.fr$/,
  /(^|\.)pantheonsorbonne\.fr$/,
  /(^|\.)parisnanterre\.fr$/,
  /(^|\.)cyu\.fr$/,
  /(^|\.)uphf\.fr$/,
  /(^|\.)unilim\.fr$/,
  /(^|\.)unicaen\.fr$/,
  /(^|\.)unistra\.fr$/,
  /(^|\.)unilasalle\.fr$/,
  /(^|\.)univ-catholille\.fr$/,
  /(^|\.)icp\.fr$/,
  /(^|\.)ucly\.fr$/,
  /(^|\.)uco\.fr$/,
  /(^|\.)ens\.fr$/,
  /(^|\.)ens-[a-z-]+\.fr$/,
  /(^|\.)ens-paris-saclay\.fr$/,
  /(^|\.)ensam\.eu$/,
  /(^|\.)insa-[a-z-]+\.fr$/,
  /(^|\.)utc\.fr$/,
  /(^|\.)utt\.fr$/,
  /(^|\.)utbm\.fr$/,
  /(^|\.)centralesupelec\.fr$/,
  /(^|\.)centrale-[a-z]+\.fr$/,
  /(^|\.)ec-[a-z]+\.fr$/,
  /(^|\.)polytechnique\.edu$/,
  /(^|\.)polytechnique\.fr$/,
  /(^|\.)mines-[a-z-]+\.fr$/,
  /(^|\.)minesparis\.psl\.eu$/,
  /(^|\.)psl\.eu$/,
  /(^|\.)dauphine\.eu$/,
  /(^|\.)dauphine\.psl\.eu$/,
  /(^|\.)sciencespo\.fr$/,
  /(^|\.)sciencespo-[a-z]+\.fr$/,
  /(^|\.)hec\.edu$/,
  /(^|\.)hec\.fr$/,
  /(^|\.)essec\.edu$/,
  /(^|\.)edhec\.edu$/,
  /(^|\.)edhec\.com$/,
  /(^|\.)escp\.eu$/,
  /(^|\.)em-lyon\.com$/,
  /(^|\.)emlyon\.com$/,
  /(^|\.)audencia\.com$/,
  /(^|\.)neoma-bs\.fr$/,
  /(^|\.)kedgebs\.com$/,
  /(^|\.)skema\.edu$/,
  /(^|\.)grenoble-em\.com$/,
  /(^|\.)tbs-education\.fr$/,
  /(^|\.)rennes-sb\.com$/,
  /(^|\.)montpellier-bs\.com$/,
  /(^|\.)excelia-group\.com$/,
  /(^|\.)ieseg\.fr$/,
  /(^|\.)essca\.fr$/,
  /(^|\.)esdes\.fr$/,
  /(^|\.)em-normandie\.fr$/,
  /(^|\.)em-strasbourg\.eu$/,
  /(^|\.)inseec\.com$/,
  /(^|\.)epita\.fr$/,
  /(^|\.)epitech\.eu$/,
  /(^|\.)esiea\.fr$/,
  /(^|\.)efrei\.fr$/,
  /(^|\.)efrei\.net$/,
  /(^|\.)supinfo\.com$/,
  /(^|\.)hetic\.net$/,
  /(^|\.)ynov\.com$/,
  /(^|\.)iim\.fr$/,
  /(^|\.)esiee\.fr$/,
  /(^|\.)esiee-paris\.fr$/,
  /(^|\.)isep\.fr$/,
  /(^|\.)ece\.fr$/,
  /(^|\.)esilv\.fr$/,
  /(^|\.)devinci\.fr$/,
  /(^|\.)ensta-paris\.fr$/,
  /(^|\.)ensta-bretagne\.fr$/,
  /(^|\.)ensae\.fr$/,
  /(^|\.)ensai\.fr$/,
  /(^|\.)enpc\.fr$/,
  /(^|\.)eivp-paris\.fr$/,
  /(^|\.)estp\.fr$/,
  /(^|\.)esiee-amiens\.fr$/,
  /(^|\.)imt-atlantique\.fr$/,
  /(^|\.)imt-[a-z-]+\.fr$/,
  /(^|\.)telecom-paris\.fr$/,
  /(^|\.)telecom-sudparis\.eu$/,
  /(^|\.)telecom-st-etienne\.fr$/,
  /(^|\.)eurecom\.fr$/,
  /(^|\.)ensimag\.fr$/,
  /(^|\.)grenoble-inp\.fr$/,
  /(^|\.)toulouse-inp\.fr$/,
  /(^|\.)bordeaux-inp\.fr$/,
  /(^|\.)enseeiht\.fr$/,
  /(^|\.)isae-supaero\.fr$/,
  /(^|\.)isae\.fr$/,
  /(^|\.)estaca\.fr$/,
  /(^|\.)ensma\.fr$/,
  /(^|\.)enac\.fr$/,
  /(^|\.)agroparistech\.fr$/,
  /(^|\.)agrocampus-ouest\.fr$/,
  /(^|\.)institut-agro\.fr$/,
  /(^|\.)vet-alfort\.fr$/,
  /(^|\.)oniris-nantes\.fr$/,
  /(^|\.)ensa-[a-z-]+\.fr$/,
  /(^|\.)ensba-lyon\.fr$/,
  /(^|\.)ensad\.fr$/,
  /(^|\.)ensci\.com$/,
  /(^|\.)lecolededesign\.com$/,
  /(^|\.)gobelins\.fr$/,
  /(^|\.)cnsmdp\.fr$/,
  /(^|\.)cnsmd-lyon\.fr$/,
  /(^|\.)femis\.fr$/,
  /(^|\.)ehess\.fr$/,
  /(^|\.)ephe\.psl\.eu$/,
  /(^|\.)inalco\.fr$/,
  /(^|\.)enssib\.fr$/,
  /(^|\.)cnam\.fr$/,
  /(^|\.)lecnam\.net$/,
  /(^|\.)ehesp\.fr$/,
  /(^|\.)ensp\.fr$/,
  /(^|\.)ira-[a-z]+\.gouv\.fr$/,
  /(^|\.)insp\.gouv\.fr$/,
  /(^|\.)uqam\.ca$/,
  /(^|\.)umontreal\.ca$/,
  /(^|\.)ulaval\.ca$/,
  /(^|\.)usherbrooke\.ca$/,
  /(^|\.)uottawa\.ca$/,
  /(^|\.)mcgill\.ca$/,
  /(^|\.)polymtl\.ca$/,
  /(^|\.)hec\.ca$/,
  /(^|\.)etsmtl\.ca$/,
  /(^|\.)uqac\.ca$/,
  /(^|\.)uqar\.ca$/,
  /(^|\.)uqat\.ca$/,
  /(^|\.)uqo\.ca$/,
  /(^|\.)uqtr\.ca$/,
  /(^|\.)ulb\.be$/,
  /(^|\.)uclouvain\.be$/,
  /(^|\.)ulg\.be$/,
  /(^|\.)uliege\.be$/,
  /(^|\.)unamur\.be$/,
  /(^|\.)umons\.be$/,
  /(^|\.)ugent\.be$/,
  /(^|\.)kuleuven\.be$/,
  /(^|\.)vub\.be$/,
  /(^|\.)uantwerpen\.be$/,
  /(^|\.)unige\.ch$/,
  /(^|\.)unil\.ch$/,
  /(^|\.)epfl\.ch$/,
  /(^|\.)ethz\.ch$/,
  /(^|\.)unifr\.ch$/,
  /(^|\.)unine\.ch$/,
  /(^|\.)unibe\.ch$/,
  /(^|\.)uzh\.ch$/,
  /(^|\.)unibas\.ch$/,
  /(^|\.)usi\.ch$/,
  /(^|\.)hes-so\.ch$/,
  /(^|\.)uni\.lu$/,
];

function domaineDe(email: string): string | null {
  const propre = email.trim().toLowerCase();
  const arobase = propre.lastIndexOf('@');

  if (arobase <= 0 || arobase === propre.length - 1) return null;

  const domaine = propre.slice(arobase + 1);

  if (!/^[a-z0-9.-]+\.[a-z]{2,}$/.test(domaine)) return null;

  return domaine;
}

function domainesDeclares(): string[] {
  return (process.env.STUDENT_EMAIL_DOMAINS ?? '')
    .split(',')
    .map((valeur) => valeur.trim().toLowerCase())
    .filter(Boolean);
}

export function estUneAdresseDEcole(email: string): boolean {
  const domaine = domaineDe(email);

  if (!domaine) return false;

  if (
    domainesDeclares().some(
      (declare) => domaine === declare || domaine.endsWith(`.${declare}`),
    )
  ) {
    return true;
  }

  if (SUFFIXES_ACADEMIQUES.some((suffixe) => domaine.endsWith(suffixe))) {
    return true;
  }

  if (PREFIXES_ETUDIANTS.some((prefixe) => domaine.startsWith(prefixe))) {
    return true;
  }

  return MOTIFS_FRANCAIS.some((motif) => motif.test(domaine));
}
