export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const HOME_REPOSITORY = Symbol('HOME_REPOSITORY');
export const FAVORITE_REPOSITORY = Symbol('FAVORITE_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const PASSWORD_RESET_TOKEN = Symbol('PASSWORD_RESET_TOKEN');
export const EMAIL_SENDER = Symbol('EMAIL_SENDER');
export const IDENTITY_PROVIDER = Symbol('IDENTITY_PROVIDER');
export const SWIPE_REPOSITORY = Symbol('SWIPE_REPOSITORY');
export const HOME_SEARCH_REPOSITORY = Symbol('HOME_SEARCH_REPOSITORY');
export const MATCH_REPOSITORY = Symbol('MATCH_REPOSITORY');
export const CHAT_REPOSITORY = Symbol('CHAT_REPOSITORY');
export const MESSAGE_REPOSITORY = Symbol('MESSAGE_REPOSITORY');
export const EXCHANGE_REPOSITORY = Symbol('EXCHANGE_REPOSITORY');


export const TRANSLATOR = Symbol('TRANSLATOR');
