export const CONTINENTS = [
  'northAmerica',
  'southAmerica',
  'europe',
  'africa',
  'asia',
  'oceania',
] as const;

export const HOME_TYPES = [
  'apartment',
  'house',
  'all'
] as const;

export const HOME_CATEGORIES = [
  'NATURE',
  'BEACH',
  'CITY',
  'CULTURE',
] as const;

export const SEASONS = [
  'spring',
  'summer',
  'autumn',
  'winter'
] as const;

export const ESSENTIAL_AMENITIES = [
  'wifi', 
  'parking',
  'kitchen',
  'tv',
  'airConditioning',
  'washingMachine',
  'balcony', 
  'workspace'
] as const;

export const ENVIRONMENTS = [
  'country',
  'city',
  'seaside',
  'entertainment',
  'relax'
] as const;

export const STAY_DURATIONS = [
  '1w',
  '2w',
  '3w',
  '1m',
  '2m',
  '3m'
] as const;

export type StayDuration = typeof STAY_DURATIONS[number];

export const REGION_DESTINATIONS: Record<string, string[]> = {
  northAmerica: [
    'mexico',
    'canada',
    'california',
    'nevada',
    'oregon',
    'washington',
    'idaho',
    'montana',
    'wyoming',
    'utah',
    'arizona',
    'colorado',
    'newMexico',
    'northDakota',
    'southDakota',
    'nebraska',
    'kansas',
    'oklahoma',
    'texas',
    'minnesota',
    'iowa',
    'missouri',
    'arkansas',
    'louisiana',
    'wisconsin',
    'illinois',
    'mississippi',
    'michigan',
    'indiana',
    'ohio',
    'kentucky',
    'tennessee',
    'alabama',
    'georgia',
    'florida',
    'westVirginia',
    'virginia',
    'pennsylvania',
    'newYork',
    'maine',
    'newHampshire',
    'vermont',
    'massachusetts',
    "southCarolina",
    'northCarolina',
    'maryland',
    'delaware',
    'rhodeIsland',
    'connecticut',
    'alaska',
    'hawaii'
  ],
  southAmerica: [
    'brazil',
    'argentina',
    'colombia',
    'chile',
    'peru',
    'venezuela',
    'ecuador',
    'bolivia',
    'paraguay',
    'uruguay',
    'guyana',
    'suriname',
    'frenchGuiana'
  ],
  europe: [
    'france',
    'spain',
    'italy',
    'germany',
    'unitedKingdom',
    'netherlands',
    'belgium',
    'switzerland',
    'austria',
    'sweden',
    'norway',
    'denmark',
    'finland',
    'ireland',
    'portugal',
    'greece',
    'czechRepublic',
    'hungary',
    'poland',
    'ukraine',
    'romania',
    'bulgaria',
    'croatia',
    'serbia',
    'slovakia',
    'cyprus',
    'luxembourg',
    'malta',
    'iceland',
    'corsica',
    'noldova',
    'belarus',
    'scotland',
    'wales',
    'andorra',
    'monaco',
    'liechtenstein',
    'sanMarino',
    'vaticanCity',
    'macedonia',
    'albania',
    'montenegro',
    'kosovo',
    'montenegro',
    'crimea'
  ],
  africa: [
    'morocco',
    'tunisia',
    'egypt',
    'southAfrica',
    'kenya',
    'ghana',
    'nigeria',
    'ethiopia',
    'algeria',
    'senegal',
    'ivoryCoast',
    'cameroon',
    'madagascar',
    'sudan',
    'niger',
    'chad',
    'mali',
    'guinea',
    'equatorialGuinea',
    'centralAfricanRepublic',
  ],
  asia: [
    'japan',
    'southKorea',
    'indonesia',
    'thailand',
    'malaysia',
    'singapore',
    'philippines',
    'vietnam',
    'turkey',
    'kazakhstan',
    'mongolia',
    'qatar',
    'kuwait',
    'russia',
    'nepal',
    'laos',
    'taiwan',
    'jordan',
    'libanon',
    'cambodia',
    'birma',
    'sriLanka',
    'maldives',
    'armenia',
    'koweït',
    'emirats'
  ],
  oceania: [
    'australia',
    'newZealand',
    'fiji',
    'papuaNewGuinea',
    'samoa',
    'tonga',
    'vanuatu',
    'solomonIslands',
    'micronesia',
    'palau',
    'marshallIslands',
    'frenchPolynesia',
    'newCaledonia',
    'cookIslands'
  ],
};